In [1]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
odd_number_list = [3, 5, 8, 2]
np.array(odd_number_list)

array([3, 5, 8, 2])

In [ ]:
two_dim_list = [[1,1,1], [2,2,2], [3,3,3]]
np.array(two_dim_list)

# arange function . 
shift + tab ()
alt + enter

In [18]:
np.arange(0 , 9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.arange(0, 9, 2)

array([0, 2, 4, 6, 8])