In [20]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [22]:
odd_number_list = [3, 5, 8, 2]
np.array(odd_number_list)

array([3, 5, 8, 2])

In [ ]:
two_dim_list = [[1,1,1], [2,2,2], [3,3,3]]
np.array(two_dim_list)

# arange function . 
shift + tab ()
alt + enter

In [24]:
np.arange(0 , 9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
np.arange(0, 9, 2)

array([0, 2, 4, 6, 8])

In [39]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones(4)

array([1., 1., 1., 1.])

In [47]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [51]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [54]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# identity matrix

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])