In [25]:
import numpy as np

In [27]:
np.random.rand(3)

array([0.36247623, 0.54527905, 0.68465603])

In [29]:
np.random.rand(7)

array([0.77936996, 0.32594242, 0.16805939, 0.38631854, 0.09070403,
       0.68142074, 0.52462646])

In [31]:
np.random.rand(3,4)

array([[0.52697074, 0.10994414, 0.15793417, 0.77017099],
       [0.76303236, 0.55003365, 0.354034  , 0.31580735],
       [0.23330203, 0.41406783, 0.12621624, 0.72203034]])

In [34]:
np.random.randint(0, 50, 20)

array([29, 47, 17, 10, 23, 24, 41, 22,  5, 17, 35, 15, 32, 32, 26, 27, 22,
        1, 19, 17])

In [37]:
rand_arr = np.random.randint(0, 50, 20)

In [39]:
rand_arr

array([37, 12, 23, 29, 41, 20, 20, 18,  5, 42, 23, 17, 22,  8, 43, 38, 16,
       35, 12, 48])

In [41]:
second_arr = np.arange(20)

In [43]:
second_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
rand_arr.reshape(4,5)

array([[37, 12, 23, 29, 41],
       [20, 20, 18,  5, 42],
       [23, 17, 22,  8, 43],
       [38, 16, 35, 12, 48]])

In [47]:
rand_arr.reshape(5,5)

ValueError: cannot reshape array of size 20 into shape (5,5)

In [49]:
rand_arr.reshape(5,4)

array([[37, 12, 23, 29],
       [41, 20, 20, 18],
       [ 5, 42, 23, 17],
       [22,  8, 43, 38],
       [16, 35, 12, 48]])

In [53]:
second_arr.max()

19

In [55]:
second_arr.min()

0

In [57]:
rand_arr.max()

48

In [59]:
rand_arr.argmax()

19

In [61]:
rand_arr.min()

5

In [63]:
rand_arr.argmin()

8

In [65]:
second_arr.shape

(20,)

In [67]:
reshaped_arr = second_arr.reshape(2,10)

In [69]:
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [71]:
reshaped_arr.shape

(2, 10)

In [73]:
reshaped_arr.dtype

dtype('int64')