In [1]:
import numpy as np

In [2]:
np.random.rand(3)

array([0.58532906, 0.80836324, 0.22247065])

In [3]:
np.random.rand(7)

array([0.09667227, 0.1040218 , 0.96004183, 0.09001728, 0.31381564,
       0.34094238, 0.1328737 ])

In [4]:
np.random.rand(3,4)

array([[0.14812392, 0.57865096, 0.50864219, 0.56801456],
       [0.29357895, 0.72439541, 0.91523288, 0.05789803],
       [0.269802  , 0.13071946, 0.3052345 , 0.98989882]])

In [5]:
np.random.randint(0, 50, 20)

array([ 6, 33, 10,  5, 48, 33, 16, 16, 28, 16,  1, 30, 21, 33, 48,  6, 12,
       44, 35, 11])

In [6]:
rand_arr = np.random.randint(0, 50, 20)

In [7]:
rand_arr

array([17, 19, 31, 26, 16,  9,  8, 26, 48, 40, 15, 44, 43, 40, 26,  6, 17,
       30, 17, 14])

In [8]:
second_arr = np.arange(20)

In [9]:
second_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
rand_arr.reshape(4,5)

array([[17, 19, 31, 26, 16],
       [ 9,  8, 26, 48, 40],
       [15, 44, 43, 40, 26],
       [ 6, 17, 30, 17, 14]])

In [11]:
rand_arr.reshape(5,5)

ValueError: cannot reshape array of size 20 into shape (5,5)

In [ ]:
rand_arr.reshape(5,4)

array([[37, 12, 23, 29],
       [41, 20, 20, 18],
       [ 5, 42, 23, 17],
       [22,  8, 43, 38],
       [16, 35, 12, 48]])

In [ ]:
second_arr.max()

19

In [ ]:
second_arr.min()

0

In [ ]:
rand_arr.max()

48

In [ ]:
rand_arr.argmax()

19

In [ ]:
rand_arr.min()

5

In [ ]:
rand_arr.argmin()

8

In [ ]:
second_arr.shape

(20,)

In [ ]:
reshaped_arr = second_arr.reshape(2,10)

In [ ]:
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
reshaped_arr.shape

(2, 10)

In [ ]:
reshaped_arr.dtype

dtype('int64')