In [2]:
import numpy as np

In [3]:
int_arr = np.random.randint(0,10,10)

In [4]:
int_arr

array([7, 0, 5, 1, 3, 7, 9, 0, 1, 5])

In [5]:
int_arr[0]

np.int64(7)

In [6]:
int_arr[9]

np.int64(5)

In [7]:
int_arr[1:3]

array([0, 5])

In [8]:
int_arr[:3]

array([7, 0, 5])

In [9]:
int_arr[3:]

array([1, 3, 7, 9, 0, 1, 5])

In [10]:
int_arr[3:10] = 10

In [11]:
int_arr

array([ 7,  0,  5, 10, 10, 10, 10, 10, 10, 10])

In [12]:
arr = np.arange(0,10)

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
new_arr = arr[:4]

In [15]:
new_arr

array([0, 1, 2, 3])

In [16]:
new_arr[2:] = 7

In [17]:
new_arr

array([0, 1, 7, 7])

In [18]:
arr

array([0, 1, 7, 7, 4, 5, 6, 7, 8, 9])

In [19]:
arr = np.arange(0,10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
new_arr = arr.copy()

In [22]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
new_arr[:] = 0

In [24]:
new_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# первоначальный массив не изменился(arr)

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# сравнение массивов

In [26]:
 arr > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [27]:
bool_arr = arr > 6

In [28]:
bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True])

# получаем выборку элементов

In [29]:
arr[bool_arr]

array([7, 8, 9])

In [30]:
arr[arr > 6]

array([7, 8, 9])

# Двумерные массивы

In [31]:
two_dim_arr = np.arange(12).reshape(3,4)

In [32]:
two_dim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
two_dim_arr[1][1]

np.int64(5)

In [34]:
two_dim_arr[1,1]

np.int64(5)

In [48]:
two_dim_arr[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [36]:
two_dim_arr[:2,:2]

array([[0, 1],
       [4, 5]])

In [37]:
two_dim_arr[0:2, 2:4]

array([[2, 3],
       [6, 7]])

In [38]:
two_dim_arr[0:2, 2:]

array([[2, 3],
       [6, 7]])

In [39]:
two_dim_arr[two_dim_arr > 4]

array([ 5,  6,  7,  8,  9, 10, 11])

# Операции с массивами

In [40]:
arr = np.arange(1,11)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [45]:
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
arr / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        , 2.33333333, 2.66666667, 3.        , 3.33333333])

In [47]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])